# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEssaie():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_essaie(self):
    # Test name: essaie
    # Step # | name | target | value | comment
    # 1 | open | http://localhost:3000/ |  | 
    self.driver.get("http://localhost:3000/")
    # 2 | setWindowSize | 1356x728 |  | 
    self.driver.set_window_size(1356, 728)
    # 3 | click | name=title |  | 
    self.driver.find_element(By.NAME, "title").click()
    # 4 | click | name=title |  | 
    self.driver.find_element(By.NAME, "title").click()
    # 5 | click | name=title |  | 
    self.driver.find_element(By.NAME, "title").click()
    # 6 | doubleClick | name=title |  | 
    element = self.driver.find_element(By.NAME, "title")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 7 | click | name=genre |  | 
    self.driver.find_element(By.NAME, "genre").click()
    # 8 | type | name=genre | Diary Holders, Adventure | 
    self.driver.find_element(By.NAME, "genre").send_keys("Diary Holders, Adventure")
    # 9 | click | css=label:nth-child(5) > input |  | 
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(5) > input").click()
    # 10 | type | css=label:nth-child(5) > input | jeune qui se debrouille pour se demarquer , | 
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(5) > input").send_keys("jeune qui se debrouille pour se demarquer ,")
    # 11 | click | name=type |  | 
    self.driver.find_element(By.NAME, "type").click()
    # 12 | type | name=type | TV | 
    self.driver.find_element(By.NAME, "type").send_keys("TV")
    # 13 | click | name=producer |  | 
    self.driver.find_element(By.NAME, "producer").click()
    # 14 | type | name=producer | aucun | 
    self.driver.find_element(By.NAME, "producer").send_keys("aucun")
    # 15 | click | name=studio |  | 
    self.driver.find_element(By.NAME, "studio").click()
    # 16 | type | name=studio | WAO World | 
    self.driver.find_element(By.NAME, "studio").send_keys("WAO World")
    # 17 | click | name=title |  | 
    self.driver.find_element(By.NAME, "title").click()
    # 18 | type | name=title | test | 
    self.driver.find_element(By.NAME, "title").send_keys("test")
    # 19 | click | css=button |  | 
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    # 20 | click | css=h2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "h2").click()
    # 21 | click | css=h2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "h2").click()
    # 22 | doubleClick | css=h2 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "h2")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
  
