global:
  scrape_interval: 5s

scrape_configs:
  

  - job_name: 'backend'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['f731e5f5f643:5000']

  - job_name: 'node'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ecb397a2b13c:9100']

rule_files:
  - /etc/prometheus/rules/rules.yml