FROM python:3.9

WORKDIR /Backend

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN python -c "import nltk; nltk.download('punkt')"


COPY . .

EXPOSE 5000

CMD ["python", "app.py"]
